/**
 * Crisis keywords for detection.
 * Used to identify when user or Sofia's response contains crisis indicators.
 * @constant {string[]}
 */
export const CRISIS_KEYWORDS = [
  'suicídio',
  'suicida',
  'morrer',
  'morte',
  'matar',
  'automutilação',
  'cortar',
  'corto',
  'cortei',
  'desistir',
  'desisto',
  'desisti',
  'crise',
  'emergência',
  'emergência psicológica',
  'pânico',
  'pânico total',
  'desesperado',
  'desesperada',
  'desespero',
  'não aguento',
  'não consigo',
  'não tenho motivo',
  'não tem razão',
  'fim da vida',
  'acabar com tudo',
  'cansei de viver',
  'cansado de viver',
  'cansada de viver',
  'melhor sozinho',
  'melhor morrer',
  'pior que morrer',
  'chute na porta',
  '188',
  'cvv',
  'telefone de ajuda',
  'risco de vida',
  'perigo iminente',
];
